package by.epam.carrental.command;

public enum CommandName {
    TO_REGISTRATION, LOGIN_USER, REGISTER, CHANGE_LOCALE, LOG_OUT_USER,
    VIEW_TYPE, VIEW_CAR, MAKE_ORDER, TO_MAKE_ORDER, VIEW_ORDERS_USER,
    VIEW_ORDER_USER, VIEW_ORDERS_ADMIN, VIEW_ORDER_ADMIN, UPDATE_STATUS, UPDATE_REAL_DATE_FROM, UPDATE_REAL_DATE_TO,
    UPDATE_DAMAGE_PRICE, VIEW_ALL_CARS, TO_PRIV_OFFICE_USER, TO_PRIV_OFFICE_ADMIN, TO_HOME_PAGE, VIEW_ALL_UNUSED_CARS,
    CANCEL_ORDER, TO_PAYMENT_PAGE, PAY, PAY_FOR_DAMAGE, VIEW_ALL_USERS, VIEW_USER, TO_ADD_CAR, TAKE_MODELS, ADD_CAR,
    DELETE_CAR, VIEW_TYPE_BY_DATE, VIEW_TYPE_UNUSED
}
